// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Books          string
	GorpMigrations string
	Topics         string
	Users          string
}{
	Books:          "books",
	GorpMigrations: "gorp_migrations",
	Topics:         "topics",
	Users:          "users",
}
