development:
  dialect: postgres
  datasource: user=postgres password=postgresv port=5442 dbname=bookstore-api-db sslmode=disable
  
dev:
  dialect: postgres
  datasource: host=${DB_HOST} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=disable

test:
  dialect: postgres
  datasource: user=postgres password=postgres port=5443 dbname=bookstore-api-db-test sslmode=disable

prod:
  dialect: postgres
  datasource: host=${DB_HOST} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=disable