version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bookstore-api-db
    environment:
      POSTGRES_DB: bookstore-api-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5432"
    networks:
      - bookstore-api-network
    volumes:
      - bookstore-api-data:/var/lib/postgresql/data

  db-test:
    image: postgres:15
    container_name: bookstore-api-db-test
    environment:
      POSTGRES_DB: bookstore-api-db-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5443:5432"  # Map to a different port to avoid conflicts with dev DB
    networks:
      - bookstore-api-network
    volumes:
      - bookstore-api-data-test:/var/lib/postgresql/data

networks:
  bookstore-api-network:

volumes:
  bookstore-api-data:
  bookstore-api-data-test:
