// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dwarvesf/bookstore-api/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// GetTopics provides a mock function with given fields: ctx
func (_m *Controller) GetTopics(ctx context.Context) ([]model.Topic, error) {
	ret := _m.Called(ctx)

	var r0 []model.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Topic, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Topic); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_GetTopics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopics'
type Controller_GetTopics_Call struct {
	*mock.Call
}

// GetTopics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Controller_Expecter) GetTopics(ctx interface{}) *Controller_GetTopics_Call {
	return &Controller_GetTopics_Call{Call: _e.mock.On("GetTopics", ctx)}
}

func (_c *Controller_GetTopics_Call) Run(run func(ctx context.Context)) *Controller_GetTopics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Controller_GetTopics_Call) Return(_a0 []model.Topic, _a1 error) *Controller_GetTopics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_GetTopics_Call) RunAndReturn(run func(context.Context) ([]model.Topic, error)) *Controller_GetTopics_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
